package com.zql.app_ji.Model.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zql.app_ji.Bean.Entity.MovieEntity;
import com.zql.app_ji.Bean.Entity.WanEntity;
import com.zql.app_ji.Bean.Entity.ZhihuEntity;

import com.zql.app_ji.Model.greendao.db.MovieEntityDao;
import com.zql.app_ji.Model.greendao.db.WanEntityDao;
import com.zql.app_ji.Model.greendao.db.ZhihuEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieEntityDaoConfig;
    private final DaoConfig wanEntityDaoConfig;
    private final DaoConfig zhihuEntityDaoConfig;

    private final MovieEntityDao movieEntityDao;
    private final WanEntityDao wanEntityDao;
    private final ZhihuEntityDao zhihuEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieEntityDaoConfig = daoConfigMap.get(MovieEntityDao.class).clone();
        movieEntityDaoConfig.initIdentityScope(type);

        wanEntityDaoConfig = daoConfigMap.get(WanEntityDao.class).clone();
        wanEntityDaoConfig.initIdentityScope(type);

        zhihuEntityDaoConfig = daoConfigMap.get(ZhihuEntityDao.class).clone();
        zhihuEntityDaoConfig.initIdentityScope(type);

        movieEntityDao = new MovieEntityDao(movieEntityDaoConfig, this);
        wanEntityDao = new WanEntityDao(wanEntityDaoConfig, this);
        zhihuEntityDao = new ZhihuEntityDao(zhihuEntityDaoConfig, this);

        registerDao(MovieEntity.class, movieEntityDao);
        registerDao(WanEntity.class, wanEntityDao);
        registerDao(ZhihuEntity.class, zhihuEntityDao);
    }
    
    public void clear() {
        movieEntityDaoConfig.clearIdentityScope();
        wanEntityDaoConfig.clearIdentityScope();
        zhihuEntityDaoConfig.clearIdentityScope();
    }

    public MovieEntityDao getMovieEntityDao() {
        return movieEntityDao;
    }

    public WanEntityDao getWanEntityDao() {
        return wanEntityDao;
    }

    public ZhihuEntityDao getZhihuEntityDao() {
        return zhihuEntityDao;
    }

}
