package com.zql.app_ji.Model.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zql.app_ji.Bean.Entity.WanEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "WAN_ENTITY".
*/
public class WanEntityDao extends AbstractDao<WanEntity, Long> {

    public static final String TABLENAME = "WAN_ENTITY";

    /**
     * Properties of entity WanEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Wan_url = new Property(2, String.class, "wan_url", false, "WAN_URL");
    }


    public WanEntityDao(DaoConfig config) {
        super(config);
    }
    
    public WanEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WAN_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: Id
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"WAN_URL\" TEXT NOT NULL );"); // 2: wan_url
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WAN_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, WanEntity entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getWan_url());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, WanEntity entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getWan_url());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public WanEntity readEntity(Cursor cursor, int offset) {
        WanEntity entity = new WanEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.getString(offset + 1), // title
            cursor.getString(offset + 2) // wan_url
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, WanEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setWan_url(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(WanEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(WanEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(WanEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
