package com.zql.app_ji.Model.greendao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zql.app_ji.Bean.Entity.ZhihuEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ZHIHU_ENTITY".
*/
public class ZhihuEntityDao extends AbstractDao<ZhihuEntity, Long> {

    public static final String TABLENAME = "ZHIHU_ENTITY";

    /**
     * Properties of entity ZhihuEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "Id", true, "_id");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Note_id = new Property(2, String.class, "note_id", false, "NOTE_ID");
    }


    public ZhihuEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ZhihuEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ZHIHU_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: Id
                "\"TITLE\" TEXT NOT NULL ," + // 1: title
                "\"NOTE_ID\" TEXT NOT NULL );"); // 2: note_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ZHIHU_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ZhihuEntity entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getNote_id());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ZhihuEntity entity) {
        stmt.clearBindings();
 
        Long Id = entity.getId();
        if (Id != null) {
            stmt.bindLong(1, Id);
        }
        stmt.bindString(2, entity.getTitle());
        stmt.bindString(3, entity.getNote_id());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ZhihuEntity readEntity(Cursor cursor, int offset) {
        ZhihuEntity entity = new ZhihuEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // Id
            cursor.getString(offset + 1), // title
            cursor.getString(offset + 2) // note_id
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ZhihuEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.getString(offset + 1));
        entity.setNote_id(cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ZhihuEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ZhihuEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ZhihuEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
